name: w_sharme_beauty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  go_router: ^13.2.2
  injectable: ^2.4.1
  intl_phone_field: ^3.2.0
  json_annotation: ^4.8.1
  pinput: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.4.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile/
    - assets/icons/

  fonts:
    - family: GTEastiProDisplay
      fonts:
        - asset: assets/fonts/GT Eesti Pro Display Regular.otf

flutter_gen:
  integrations:
    flutter_svg: true
